app_homepage:
    path: /
    controller: App\Controller\DefaultController::index

a_propos:
    path: /a-propos
    controller: App\Controller\AProposController::index

cours:
    path: /cours
    controller: App\Controller\CoursController::index

newsletter:
    path: /newsletter
    controller: App\Controller\NewsletterController::index

contact:
    path: /contact
    controller: App\Controller\ContactController::index

inscription:
    path: /inscription
    controller: App\Controller\InscriptionController::index

connexion:
    path: /connexion
    controller: App\Controller\ConnexionController::index

app_newsletter:
    path: /newsletter
    controller: App\Controller\NewsletterController::index

newsletter_confirmation:
    path: /newsletter/confirmation
    controller: App\Controller\NewsletterController::confirmation

